name: Deploy DecentralizedDB

on: 
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      mongodb:
        image: mongo:latest
        ports:
          - 27017:27017

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'

      - name: Install Dependencies
        run: |
          npm install -g concurrently
          npm install
          npm install -w frontend
          npm install -w backend
          npm install -w frontend react-router-dom react-icons axios


      - name: Wait for MongoDB to initialize
        run: sleep 30

      - name: Build Frontend
        run: |
          cd frontend
          npm run build

      - name: Start Backend
        run: |
          cd backend
          npm run start &
          sleep 10  # Wait for backend to initialize

      - name: Serve Frontend
        run: |
          cd frontend
          npm install -g serve
          serve -s dist -l 5173 &
          sleep 10  # Wait for frontend to initialize

      - name: Verify Services
        run: |
          curl -f http://0.0.0.0:4000/ || echo "⚠️ Backend may not be responding"
          curl -f http://0.0.0.0:5173/ || echo "⚠️ Frontend may not be responding"

      - name: Success Message
        run: echo "✅ Backend and Frontend started successfully!"

      - name: Deploy Frontend to GitHub Pages
        if: success()
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./frontend/dist


